name: Push Notification
on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
        - name: Send notification email
          uses: dawidd6/action-send-mail@v3
          with:
            server_address: smtp.gmail.com    # SMTP server address
            server_port: 465                  # SMTP server port
            username: ${{ secrets.EMAIL }}    # Mail gönderilecek, mail adresi
            password: ${{ secrets.PASSWORD }} # Mail gönderilecek, mail adresinin şifresi ()
            subject: 'Push Notification'      # Mail konusu
            body: 'Push Notification'         # Mail içeriği
            to: ${{ secrets.EMAIL_TO }}       # Mail gönderilecek, mail adresi
            from: ${{ secrets.EMAIL_FROM }}   # Mail gönderen, mail adresi 